-- Laboratory Work #3 - DML Operations

-- PART A. DATABASE AND TABLE SETUP
-- Run this statement while connected to the default "postgres" database. Then connect to the new "advanced_lab" database in DataGrip.

CREATE DATABASE advanced_lab;

-- The remaining statements must be executed while connected to advanced_lab.

CREATE TABLE employees (
    emp_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(50) NOT NULL,
    last_name   VARCHAR(50) NOT NULL,
    department  VARCHAR(100) DEFAULT 'Unassigned',
    salary      INTEGER DEFAULT 0,
    hire_date   DATE,
    status      VARCHAR(20) DEFAULT 'Active'
);

CREATE TABLE departments (
    dept_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name   VARCHAR(100) NOT NULL,
    budget      INTEGER NOT NULL DEFAULT 0,
    manager_id  INTEGER
);

CREATE TABLE projects (
    project_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(100) NOT NULL,
    dept_id      INTEGER,
    start_date   DATE,
    end_date     DATE,
    budget       INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_project_department
        FOREIGN KEY (dept_id)
        REFERENCES departments(dept_id)
        ON DELETE SET NULL
);

-- SAMPLE DATA

INSERT INTO employees (first_name, last_name, department, salary, hire_date, status)
VALUES
    ('Alice', 'Brown', 'IT', 70000, '2019-03-10', 'Active'),
    ('Bob', 'Smith', 'Sales', 55000, '2021-06-15', 'Active'),
    ('Carol', 'White', 'HR', 45000, '2022-01-20', 'Active'),
    ('David', 'Green', 'IT', 90000, '2018-11-05', 'Active'),
    ('Emma', 'Jones', 'Sales', 65000, '2019-08-25', 'Inactive'),
    ('Frank', 'Miller', 'IT', 40000, '2023-05-10', 'Terminated'),
    ('Grace', 'Taylor', 'Finance', 75000, '2020-02-17', 'Active'),
    ('Henry', 'Wilson', NULL, 35000, '2024-01-10', 'Active'),
    ('Ivy', 'Davis', 'IT', 80000, '2017-09-12', 'Active');

INSERT INTO departments (dept_name, budget, manager_id)
VALUES
    ('IT', 150000, 1),
    ('Sales', 90000, 2),
    ('HR', 70000, 3);

INSERT INTO projects (project_name, dept_id, start_date, end_date, budget)
VALUES
    ('Legacy Project', 1, '2021-01-01', '2022-12-31', 60000),
    ('New Platform', 1, '2024-01-01', '2026-12-31', 80000),
    ('Sales Portal', 2, '2024-02-01', '2026-11-30', 45000),
    ('HR System', 3, '2024-03-01', '2026-10-31', 30000);

-- PART B. ADVANCED INSERT OPERATIONS

-- 2. INSERT with column specification.
INSERT INTO employees (emp_id, first_name, last_name, department)
VALUES (100, 'John', 'Carter', 'IT');

-- 3. INSERT with DEFAULT values.
INSERT INTO employees (first_name, last_name, department, salary, status)
VALUES ('Kate', 'Brown', 'HR', DEFAULT, DEFAULT);

-- 4. INSERT multiple rows in one statement.
INSERT INTO departments (dept_name, budget, manager_id)
VALUES
    ('Marketing', 120000, NULL),
    ('Research', 200000, NULL),
    ('Support', 80000, NULL);

-- 5. INSERT with expressions.
INSERT INTO employees (first_name, last_name, salary, hire_date)
VALUES ('Liam', 'Wilson', 50000 * 1.1, CURRENT_DATE);

-- 6. INSERT from SELECT (subquery).

CREATE TEMPORARY TABLE temp_employees (
    emp_id      INTEGER,
    first_name  VARCHAR(50),
    last_name   VARCHAR(50),
    department  VARCHAR(100),
    salary      INTEGER,
    hire_date   DATE,
    status      VARCHAR(20)
);

INSERT INTO temp_employees
SELECT emp_id, first_name, last_name, department, salary, hire_date, status
FROM employees
WHERE department = 'IT';

-- PART C. COMPLEX UPDATE OPERATIONS

-- 7. UPDATE with arithmetic expression.
UPDATE employees
SET salary = salary * 1.10
WHERE salary IS NOT NULL;

-- 8. UPDATE with WHERE and multiple conditions.
UPDATE employees
SET status = 'Senior'
WHERE salary > 60000
  AND hire_date < DATE '2020-01-01';

-- 9. UPDATE using CASE expression.
UPDATE employees
SET department =
    CASE
        WHEN salary > 80000 THEN 'Management'
        WHEN salary BETWEEN 50000 AND 80000 THEN 'Senior'
        ELSE 'Junior'
    END
WHERE salary IS NOT NULL;

-- 10. UPDATE with DEFAULT.
UPDATE employees
SET department = DEFAULT
WHERE status = 'Inactive';

-- 11. UPDATE with a correlated subquery.
UPDATE departments AS d
SET budget = (
    SELECT CAST(AVG(e.salary) * 1.20 AS INTEGER)
    FROM employees AS e
    WHERE e.department = d.dept_name
)
WHERE EXISTS (
    SELECT 1
    FROM employees AS e
    WHERE e.department = d.dept_name
);

-- 12. UPDATE multiple columns in one statement.
INSERT INTO employees (first_name, last_name, department, salary, hire_date, status)
VALUES ('Sales', 'Test', 'Sales', 60000, CURRENT_DATE, 'Active');

UPDATE employees
SET salary = salary * 1.15,
    status = 'Promoted'
WHERE department = 'Sales';

-- PART D. ADVANCED DELETE OPERATIONS

-- 13. DELETE with a simple WHERE condition.
DELETE FROM employees
WHERE status = 'Terminated';

-- 14. DELETE with a complex WHERE clause.
INSERT INTO employees (first_name, last_name, salary, hire_date, department, status)
VALUES ('Test', 'Delete', 30000, '2024-01-01', NULL, 'Active');

DELETE FROM employees
WHERE salary < 40000
  AND hire_date > DATE '2023-01-01'
  AND department IS NULL;

-- 15. DELETE with a subquery.
DELETE FROM departments AS d
WHERE NOT EXISTS (
    SELECT 1
    FROM employees AS e
    WHERE e.department = d.dept_name
);

-- 16. DELETE with RETURNING.
DELETE FROM projects
WHERE end_date < DATE '2023-01-01'
RETURNING *;

-- PART E. OPERATIONS WITH NULL VALUES

-- 17. INSERT with NULL values.
INSERT INTO employees (first_name, last_name, salary, department, hire_date, status)
VALUES ('Null', 'Example', NULL, NULL, CURRENT_DATE, 'Active');

-- 18. UPDATE NULL handling.
UPDATE employees
SET department = 'Unassigned'
WHERE department IS NULL;

-- 19. DELETE with NULL conditions.
DELETE FROM employees
WHERE salary IS NULL
   OR department IS NULL;

-- PART F. RETURNING CLAUSE OPERATIONS

-- 20. INSERT with RETURNING.
INSERT INTO employees (first_name, last_name, department, salary, hire_date)
VALUES ('Nora', 'Taylor', 'IT', 62000, CURRENT_DATE)
RETURNING emp_id, first_name || ' ' || last_name AS full_name;

-- 21. UPDATE with RETURNING.
WITH old_values AS (
    SELECT emp_id, salary AS old_salary
    FROM employees
    WHERE department = 'IT'
)
UPDATE employees AS e
SET salary = e.salary + 5000
FROM old_values AS o
WHERE e.emp_id = o.emp_id
RETURNING e.emp_id, o.old_salary, e.salary AS new_salary;

-- 22. DELETE with RETURNING all columns.
INSERT INTO employees (first_name, last_name, department, salary, hire_date, status)
VALUES ('Old', 'Employee', 'HR', 42000, '2019-01-01', 'Active');

DELETE FROM employees
WHERE hire_date < DATE '2020-01-01'
RETURNING *;

-- PART G. ADVANCED DML PATTERNS

-- 23. Conditional INSERT using WHERE NOT EXISTS.
INSERT INTO employees (first_name, last_name, department, salary, hire_date, status)
SELECT 'Olivia', 'Martin', 'HR', 58000, CURRENT_DATE, 'Active'
WHERE NOT EXISTS (
    SELECT 1
    FROM employees
    WHERE first_name = 'Olivia'
      AND last_name = 'Martin'
);

-- 24. UPDATE with JOIN logic using a subquery.
UPDATE employees AS e
SET salary =
    e.salary *
    CASE
        WHEN (
            SELECT d.budget
            FROM departments AS d
            WHERE d.dept_name = e.department
        ) > 100000
        THEN 1.10
        ELSE 1.05
    END
WHERE e.salary IS NOT NULL;

-- 25. Bulk operations.
INSERT INTO employees (first_name, last_name, department, salary, hire_date, status)
VALUES
    ('Paul', 'Adams', 'IT', 50000, CURRENT_DATE, 'Active'),
    ('Quinn', 'Baker', 'Sales', 51000, CURRENT_DATE, 'Active'),
    ('Rachel', 'Clark', 'HR', 52000, CURRENT_DATE, 'Active'),
    ('Sam', 'Evans', 'Finance', 53000, CURRENT_DATE, 'Active'),
    ('Tina', 'Fox', 'IT', 54000, CURRENT_DATE, 'Active');

UPDATE employees
SET salary = salary * 1.10
WHERE (first_name, last_name) IN (
    ('Paul', 'Adams'),
    ('Quinn', 'Baker'),
    ('Rachel', 'Clark'),
    ('Sam', 'Evans'),
    ('Tina', 'Fox')
);

-- 26. Data migration simulation.
CREATE TABLE employee_archive (
    emp_id      INTEGER PRIMARY KEY,
    first_name  VARCHAR(50) NOT NULL,
    last_name   VARCHAR(50) NOT NULL,
    department  VARCHAR(100),
    salary      INTEGER,
    hire_date   DATE,
    status      VARCHAR(20)
);

-- Copy inactive employees to the archive.
INSERT INTO employee_archive (
    emp_id, first_name, last_name, department, salary, hire_date, status
)
SELECT emp_id, first_name, last_name, department, salary, hire_date, status
FROM employees
WHERE status = 'Inactive';

-- Delete the migrated rows from the original table.
DELETE FROM employees
WHERE status = 'Inactive';

-- 27. Complex business logic.
INSERT INTO employees (first_name, last_name, department, salary, hire_date, status)
VALUES
    ('TestIT1', 'User', 'IT', 45000, CURRENT_DATE, 'Active'),
    ('TestIT2', 'User', 'IT', 45000, CURRENT_DATE, 'Active'),
    ('TestIT3', 'User', 'IT', 45000, CURRENT_DATE, 'Active'),
    ('TestIT4', 'User', 'IT', 45000, CURRENT_DATE, 'Active');

-- Extend a project by 30 days when its budget is > 50000 and its department has more than 3 employees.
UPDATE projects AS p
SET end_date = p.end_date + INTERVAL '30 days'
WHERE p.budget > 50000
  AND (
      SELECT COUNT(*)
      FROM employees AS e
      WHERE e.department = (
          SELECT d.dept_name
          FROM departments AS d
          WHERE d.dept_id = p.dept_id
      )
  ) > 3;
